I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 164, in script
    with Disslove(1)
  File "game/script.rpy", line 164, in <module>
    with Disslove(1)
NameError: name 'Disslove' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 164, in script
    with Disslove(1)
  File "D:\Renpy\renpy-8.1.3-sdk\renpy\ast.py", line 1671, in execute
    trans = renpy.python.py_eval(self.expr)
  File "D:\Renpy\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Renpy\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 164, in <module>
    with Disslove(1)
NameError: name 'Disslove' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
About Faces 1.0
Tue Nov 14 14:46:47 2023
